

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'TBTUIKit_Example' do
  pod 'TBTUIKit', :path => '../'

  target 'TBTUIKit_Tests' do
    inherit! :search_paths

    
  end
end
